### ISSUE TITLE
ანგარიშის შექმნის ფუნქციონალი

### ISSUE THREAD

**Issue by LeriGogoladze** [LeriGogoladze/Int-bank#1]
ანგარიშის შექმნა:

მომხმარებელები შექმნიან ახალ საბანკო ანგარიშსს მათი სახელისა და საწყისი ბალანსის შეყვანით, საწყისი ბალანსი არ უნდა იყოს 100 ლარზე მეტი.
სისტემა დაუგენერირებს უნიკალურ ანგარიშის ნომერს თითოეული ანგარიშისთვის (ფორმატი: TB0000 - TB9999).

**Comment by michaileee** [comment]
ანგარიშის შექმნის ფუნქციონალი შექმნის მოდული დასრულებულია
